[build]
  command = "CI= npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_APP_ENV = "production"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"