[build]
  command = "npm install --force && NEXT_PUBLIC_APP_ENV=production npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_APP_ENV = "production"
  NODE_VERSION = "20"  # Setting to a stable version compatible with Next.js 15

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200